version: "3.8"

services:
  mysql:
    image: mysql:8.0
    command: >
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: logistics
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/my.cnf:/etc/mysql/conf.d/zzz-my.cnf 
    ports:
      - "3306:3306"


  backend:
    build: ./backend
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: 1234
      DB_NAME: logistics
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    restart : always

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend