apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJMU1EUXdPVEV4TVRneE5Gb1hEVE0xTURRd056RXhNak14TkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS0VPCjZ1RmdULzU2VU1YSlR1cGsrcDNYL1A5ZHNjQjExTm4zdkd5b28xTmRuSXZHNkxtVzJGRWFIZi9BYk5Ya1FzcWkKbHorM2xWQnhDMHRjczVVc0xERXRhMEw5SzFRTzFqQ3VlZEJIS1lkVGFiWmkyMzlVRGNBZVNkazlsUGsvcm5CMQpIZjhqYUV6UEFlSEFuVkZHeXZETFM5RlgvcGJBK1I2ajhma0N2aWNJdHZUV3ppajY1VDVtK0FEWi91RWlyWi9SCkQ1emY2QWF6SXR6dGYxcHVVOHJVeFVPMmo5U2ZFekxrY2NmMW1GQ3I4M1dveGFpTEkzaFFRYXlzY2JKL3paemIKRkhGd1F5UFNwY0YyeW1DVExMd1J1cUZtdi8vSXNWT2RBZ2VnT1VMeTg0VHlqakk0bnIvMkFmOHdORlE5U0RiYQpma2RFNlg4d1lLMXltb1RPOVg4Q0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGQlpvM2ZVMGtEQlYyYm9lTWw1WmpEdUs4RC9rTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQnlZZHZiKzZHeTU2aDdXQ2ZWVEN2bXJsdTNiUCtSbU1NbXdESFc3anNVSCtHSgppSWJHeGVSZGdZOHVseHB4UU0rWlY4aW15cnhrMUN4UUJaVG83MlF1K3dGZWZPaU9meVBNN0IvU1k4SytqWmlRClJYYW9uVXAxZS95RkFXbDVqYi91WFBwejV2YTBLOWFVMVJ2RUdKa3Y3WlBSUWtudG1xL0ZSTUNxWU5kK0lEYjQKeDBzMWtqTU8wZWJnQWM3enF2czJFZmZUa2FQcnVoaUpSbm0rN3hPV2dUaDNNNjhQOWxsTG5UVGVCRTRhUnJ3dwpEczNUT3RUVFRQdVF2R0IrQlRSY0ZMNG11NkJ2cStDL0oxM1IyMW9URG84endzb3J0L0M4UlY0T1ZHdmpWcjF5CmptZTdlQ0g3MVpRV2xtL2dFbDVFTG0zbU05WkY3MTh1cXJMVXF1c3IKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://58d6c44b-be0b-4635-9e76-700a077a5f06-public.ke.kr-central-2.kakaocloud.com
  name: sfacspace
contexts:
- context:
    cluster: sfacspace
    user: sfacspace-admin
  name: sfacspace-admin@sfacspace
current-context: sfacspace-admin@sfacspace
kind: Config
preferences: {}
users:
    - name: sfacspace-admin
      user:
        exec:
          apiVersion: client.authentication.k8s.io/v1beta1
          args: null
          command: kic-iam-auth
          env:
          - name: "OS_AUTH_URL"
            value: "https://iam.kakaocloud.com/identity/v3"
          - name: "OS_AUTH_TYPE"
            value: "v3applicationcredential"
          - name: "OS_APPLICATION_CREDENTIAL_ID"
            value: "fd9f2ff1df4c449a99797dc7e873f770"
          - name: "OS_APPLICATION_CREDENTIAL_SECRET"
            value: "955cb9b203f07a03b28612b1e823349328ed8fdb8bcc4dcc22a16376d239c4da43aabf"
          - name: "OS_REGION_NAME"
            value: "kr-central-2"